### ISSUE TITLE
docker-machine 커맨드 리스트 정리

### ISSUE THREAD

**Issue by geunho** [hypergamma/instance-controller#4]
controller 서버에 docker-machine 프로그램을 통해 docker instance 관리를 한다.
아래는 로컬에서 등록한 instance list. 동작중인 container도 없고 swarm 도 없기 때문에 instance의 상태만 `Running`으로 동작 중임을 알 수 있다.
```
GeunhoKhim:instance-controller geunho$ docker-machine ls
NAME         ACTIVE   DRIVER   STATE     URL                         SWARM   DOCKER    ERRORS
gamma-dc01   -        none     Running   tcp://52.185.151.222:2376           Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc02   -        none     Running   tcp://13.76.246.233:2376            Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc03   -        none     Running   tcp://52.163.60.150:2376            Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc04   -        none     Running   tcp://52.187.40.252:2376            Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc05   -        none     Running   tcp://52.163.62.148:2376            Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc06   -        none     Running   tcp://13.76.246.135:2376            Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc07   -        none     Running   tcp://207.46.226.210:2376           Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc08   -        none     Running   tcp://52.163.94.98:2376             Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc09   -        none     Running   tcp://13.76.142.26:2376             Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
gamma-dc10   -        none     Running   tcp://52.187.46.38:2376             Unknown   Unable to query docker version: Cannot connect to the docker engine endpoint
```
action | commad | desc.
----- | --------- | -------
instance 추가 | docker-machine create --driver none --url={tcp_endpoint} {instance_name} | docker가 설치된 machine 정보를 추가
instance 제거 | docker-machine rm {instance_name} |  machine을 제거. docker 가 삭제되는 것은 아님에 주의
swarm (handler pool) 생성 | |
swarm (handler pool) 삭제 | |
swarm에 instance 추가 | |
swarm에 instance 삭제 | |

**Comment by geunho** [comment]
**check list**
- [x] tcp 연결 허용 설정 확인
- [x] self-signed 인증서 설치 방법 확인

**Comment by yuzoonc** [comment]
docker-machine create --driver none --url=tcp://52.185.151.222:2376 gamma-dc01

docker-machine create --driver none --url=tcp://13.76.246.233:2376 gamma-dc02

docker-machine create --driver none --url=tcp://52.163.60.150:2376 gamma-dc03

docker-machine create --driver none --url=tcp://52.187.40.252:2376 gamma-dc04

docker-machine create --driver none --url=tcp://52.163.62.148:2376 gamma-dc05

docker-machine create --driver none --url=tcp://13.76.246.135:2376 gamma-dc06

docker-machine create --driver none --url=tcp://207.46.226.210:2376 gamma-dc07

docker-machine create --driver none --url=tcp://52.163.94.98:2376 gamma-dc08

docker-machine create --driver none --url=tcp://13.76.142.26:2376 gamma-dc09

docker-machine create --driver none --url=tcp://52.187.46.38:2376 gamma-dc10

**Comment by yuzoonc** [comment]
docker-machine create --driver generic --generic-ip-address 52.185.151.222 --generic-ssh-user gamma gamma-dc01

docker-machine create --driver generic --generic-ip-address 13.76.246.233 --generic-ssh-user gamma gamma-dc02

docker-machine create --driver generic --generic-ip-address 52.163.60.150 --generic-ssh-user gamma gamma-dc03

docker-machine create --driver generic --generic-ip-address 52.187.40.252 --generic-ssh-user gamma gamma-dc04

docker-machine create --driver generic --generic-ip-address 52.163.62.148 --generic-ssh-user gamma gamma-dc05

docker-machine create --driver generic --generic-ip-address 13.76.246.135 --generic-ssh-user gamma gamma-dc06

docker-machine create --driver generic --generic-ip-address 207.46.226.210 --generic-ssh-user gamma gamma-dc07

docker-machine create --driver generic --generic-ip-address 52.163.94.98 --generic-ssh-user gamma gamma-dc08

docker-machine create --driver generic --generic-ip-address 13.76.142.26 --generic-ssh-user gamma gamma-dc09

docker-machine create --driver generic --generic-ip-address 52.187.46.38 --generic-ssh-user gamma gamma-dc10

**Comment by yuzoonc** [comment]
self-signed는  세팅이 너무 힘들다. 물론 방법이 있겠지만 일단은 친숙하고 익숙한 ssh-copy-id로 세팅

**Comment by geunho** [comment]
docker machine  을 사용하지 않기로 결정함.
